config/routes.rb
Rails.application.routes.draw do

  root to: "usuarios#login"

  get 'categorias_api/index'
  get 'categorias_api/obtener/:id', to: 'categorias_api#obtener'

  get 'categorias/index'
  get 'categorias', to: 'categorias#index'

  get 'categorias/new', to: 'categorias#new'
  get 'categorias/:id', to: 'categorias#show'
  post 'categorias', to: 'categorias#create'

  get 'categorias/:id/edit', to: 'categorias#edit',  as: :edit_categorium
  patch 'categorias/:id', to: 'categorias#update', as: :categorium

  delete 'categorias/:id', to: 'categorias#destroy', as: :destroy_categorium

  get 'usuarios/index', to: 'usuarios#index'
  get 'usuarios/new', to: 'usuarios#new', as: :new_usuario
  post "usuarios", to: "usuarios#create"
  get 'usuarios/:id/edit', to: "usuarios#edit", as: :edit_usuario
  patch "usuarios/:id", to: "usuarios#update", as: :usuario
  delete "usuarios/:id", to: "usuarios#delete"
  get "usuarios/login", to: "usuarios#login"
  post 'usuarios/logged', to: 'usuarios#logged'

  get 'usuarios/:id', to: "usuarios#show"

  get "users", to: "usuarios#json"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #resources :instrumentos

  get "productos", to: "instrumentos#show_json"
  get "informacion", to: "instrumentos#show_json"

  get "instrumentos", to: "instrumentos#index"
  get "instrumentos/new", to: "instrumentos#new", as: :new_instrumento
  post "instrumentos", to: "instrumentos#create"
  get "instrumentos/:id", to: "instrumentos#show"
  get "instrumentos/:id/edit", to: "instrumentos#edit", as: :edit_instrumento
  patch "instrumentos/:id", to: "instrumentos#update", as: :instrumento
  delete "instrumentos/:id", to: "instrumentos#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorium.rb
class Categorium < ApplicationRecord

  has_many :instrumentos, class_name: 'Instrumento', foreign_key: 'categoria_id'

  has_one_attached :image
  validates :nombre, presence: true
  validates :image, presence: true
  validates :descripcion, presence: true, length: { maximum: 1000 }

end

app/models/instrumento.rb
class Instrumento < ApplicationRecord

  belongs_to :categorium, class_name: 'Categorium', foreign_key: 'categoria_id'

  has_one_attached :image
  validates :nombre, presence: true, length: {minimum: 5, maximum: 50}
  validates :precio, presence: true, length: {minimum: 1, maximum: 10}
  validates :detalles, presence: true, length: {minimum: 1}
  validates :categoria_id, presence: true
  validates :color, presence: true
  validates :material, presence: true, length: {minimum: 1}
  validates :image, presence: true
  validates :informacion, presence: true
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  validates :tipo, presence: true, length: {minimum: 1, maximum: 1}
  validates :nombre, presence: true
  validates :apellidos, presence: true
  validates :pais, presence: true
  validates :localidad, presence: true
  validates :direccion, presence: true
  validates :codigoPostal, presence: true, length: {minimum: 5, maximum: 5}
  validates :email, presence: true, length: {minimum: 4}
  validates :contraseña, presence: true, length: {minimum: 8}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categorias_api_controller.rb
class CategoriasApiController < ApplicationController

  # todas las categorías '/categorias_api/index'
  def index
    @categorias = Categorium.all.with_attached_image
    render json: @categorias.map { |categoria|
      categoria.as_json.merge({ image: url_for(categoria.image) })
    }
  end

  # categoría con id = :id '/categorias_api/obtener/:id'
  def obtener
    @categoria = Categorium.find(params[:id]).with_attached_image
    render json: @categorias.map { |categoria|
      categoria.as_json.merge({ image: url_for(categoria.image) })
    }
  end
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController

  def index
    @categorias = Categorium.all()
  end

  def show
    @categoria = Categorium.find(params[:id])
  end

  def new
    @categoria = Categorium.new
  end

  def edit
    @categoria = Categorium.find(params[:id])
  end

  def create
    @categoria = Categorium.create(params_categoria)
    if @categoria.save
      redirect_to "/categorias/index"
    else
      render 'new'
    end
  end

  def update
    @categoria = Categorium.find(params[:id])
    if @categoria.update(params_categoria)
      redirect_to @categoria
    else
      render 'edit'
    end
  end

  def destroy
    @categoria = Categorium.find(params[:id])
    @categoria.destroy
    redirect_to categorias_path
  end

  private
  def params_categoria
    params.require(:categorium).permit(:nombre, :descripcion, :image)
  end

end

app/controllers/instrumentos_controller.rb
class InstrumentosController < ApplicationController

  before_action :find_instrumento, only: [:show, :edit, :update, :destroy]

  def index
    @instrumento = Instrumento.all
  end

  def new
    @instrumento = Instrumento.new
  end

  def create
    @instrumento = Instrumento.create(strong_params_instrumento)
    if @instrumento.save
      redirect_to @instrumento
    else
      render 'new'
    end
  end

  def show
  end

  def show_json
    @instrumento = Instrumento.all.with_attached_image
    render json: @instrumento.map { |instrumento|
      instrumento.as_json.merge({ image: url_for(instrumento.image) })
    }
  end

  def edit
  end

  def update
    if @instrumento.update(strong_params_instrumento)
      redirect_to @instrumento
    else
      render 'edit'
    end
  end

  def destroy
    @instrumento.destroy
    redirect_to instrumentos_path
  end

  private
    def find_instrumento
      @instrumento = Instrumento.find(params[:id])
    end

    def strong_params_instrumento
      params.require(:instrumento).permit(:nombre, :detalles, :precio,
                                          :image, :categoria_id, :color, :material, :informacion)
    end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController

  @root_url = "/usuarios/index"
  layout 'application'
  add_flash_types :notice

  def index
    @usuario = Usuario.all
  end

  def new
    @usuario = Usuario.new
  end

  def create
    @usuario = Usuario.create(params_usuarios)
    if @usuario.save
      redirect_to usuarios_index_path
    else
      render 'new'
    end
  end

  def show
    @usuario = Usuario.find(params[:id])
  end

  def edit
    @usuario = Usuario.find(params[:id])
  end

  def update
    @usuario = Usuario.find(params[:id])
    if @usuario.update(params_usuarios)
      redirect_to usuarios_index_path
    else
      render 'edit'
    end
  end

  def delete
    @usuario = Usuario.find(params[:id])
    @usuario.destroy
    redirect_to usuarios_index_path
  end

  def json
    @usuario = Usuario.all
    render json: @usuario
  end

  def login

  end

  def logged
    usuario = Usuario.find_by_nombre(params[:usuario][:nombre])
    if usuario != nil
      if usuario.contraseña == params[:usuario][:contraseña] && usuario.tipo == "1"
        session[:nombre] = usuario.nombre
        redirect_to categorias_path
      elsif usuario.contraseña == params[:usuario][:contraseña] && usuario.tipo == "2"
        redirect_to usuarios_login_path, :notice => "Este usuario no es administrador"
      else
        redirect_to usuarios_login_path, :notice => "Contraseña incorrecta"
      end
    else
      redirect_to usuarios_login_path, :notice => "No existe el usuario"
    end
  end

  private

  def params_usuarios
    params.require(:usuario).permit(:nombre, :apellidos, :pais, :localidad,
                                    :direccion, :codigoPostal, :email, :contraseña, :tipo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categorias_api_helper.rb
module CategoriasApiHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/instrumentos_helper.rb
module InstrumentosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/categorias/edit.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="my-3 content p-5">

    <div class="w-100 text-center">
      <h1>Editar categoría</h1>
      <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
    </div>

    <%= form_with(model: @categoria, local: true) do |form| %>

      <% if @categoria.errors.any? %>
        <div class="alert alert-danger">
          <span>
            Se han encontrado
            <%= pluralize(@categoria.errors.count, "error") %>:
          </span>
          <ul>
            <% @categoria.errors.full_messages.each do |msg| %>
              <li> <%= msg %> </li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :id %>
        <%= form.text_field :id, class: 'form-control', readonly: true %>
      </div>

      <div class="form-group">
        <%= form.label :nombre %>
        <%= form.text_field :nombre, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :descripcion %>
        <%= form.text_area :descripcion, class: 'form-control' %>
      </div>

      <%= image_tag @categoria.image, style: "max-width:250px", class: "rounded"%>

      <div class="form-group">
        <%= form.label :image %>
        <%= form.file_field :image, class:"form-control-file" %>
      </div>

      <%= form.submit "Guardar", class: 'btn btn-dark' %>
      <%= link_to "Cancelar", categorias_path, class: 'btn btn-primary' %>

  <% end %>
  </div>
</section>

app/views/categorias/index.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="my-3 content p-5">

    <div class="w-100 text-center">
      <h1>Categorías</h1>
      <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
    </div>

    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col" class="text-center">Nombre</th>
          <th scope="col" class="text-center">Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @categorias.each do |categoria| %>
          <tr>
            <th scope="row"><%= categoria.id %></th>
            <td class="text-center"><%= categoria.nombre %></td>
            <td class="align-middle text-center">
              <%= link_to 'Detalles', categoria, class: "btn btn-info" %>
              <%= link_to 'Editar', edit_categorium_path(categoria), class: "btn btn-success" %>
              <%= link_to 'Eliminar', categoria, method: :delete, data: { confirm: "¿Está seguro?" }, class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/categorias/leer.html.erb
<div class="container">
  <h1>Detalles de categoría</h1>
  <table class="table table-hover">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Descripcion</th>
      <th scope="col">Imagen</th>
      <th scope="col">Acciones</th>
    </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row"><%= @categoria.id %></th>
        <td><%= @categoria.nombre %></td>
        <td><%= @categoria.descripcion %></td>
        <td><%= @categoria.img %></td>
        <td class="text-center">
          <a class="btn btn-primary btn-sm" href="/categorias/actualizar/<%= @categoria.id %>">Editar</a>
          <button type="button" class="btn btn-sm btn-danger">Eliminar</button>
        </td>
      </tr>
    </tbody>
  </table>

</div>

app/views/categorias/new.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="my-3 content p-5">

    <div class="w-100 text-center">
      <h1>Nueva categoría</h1>
      <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
    </div>

    <%= form_with(model: @categoria, url: categorias_path, html: { method: :post}, local: true) do |form| %>

      <% if @categoria.errors.any? %>
        <div class="alert alert-danger">
          <span>
            Se han encontrado
            <%= pluralize(@categoria.errors.count, "error") %>:
          </span>
          <ul>
            <% @categoria.errors.full_messages.each do |msg| %>
              <li> <%= msg %> </li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :nombre %>
        <%= form.text_field :nombre, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :descripcion %>
        <%= form.text_area :descripcion, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :image %>
        <%= form.file_field :image, class:"form-control-file" %>
      </div>

      <%= form.submit "Guardar", class: 'btn btn-dark' %>
      <%= link_to "Cancelar", categorias_path, class: 'btn btn-primary' %>

    <% end %>
  </div>
</section>

app/views/categorias/show.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="my-3 content p-5">

    <div class="w-100 text-center">
      <h1>Detalles de categoría</h1>
      <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
    </div>

    <table class="table table-hover">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col" class="text-center">Nombre</th>
        <th scope="col" class="text-center">Descripcion</th>
        <th scope="col" class="text-center">Imagen</th>
        <th scope="col" class="text-center">Acciones</th>
      </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row"><%= @categoria.id %></th>
          <td class="text-center"><%= @categoria.nombre %></td>
          <td class="text-center"><%= @categoria.descripcion %></td>
          <td><%= image_tag @categoria.image, style: "max-width:250px", class: "rounded"%></td>
          <td class="text-center">
            <%= link_to 'Editar', edit_categorium_path(@categoria), class: "btn btn-success" %>
            <%= link_to 'Eliminar', @categoria, method: :delete, data: { confirm: "¿Está seguro?" },
                        class: "btn btn-danger", style: "margin-top:3px" %>
          </td>
        </tr>
      </tbody>
    </table>
    <%= link_to "Volver", categorias_path, class: 'btn btn-dark' %>

  </div>
</section>

app/views/instrumentos/edit.html.erb
<section class="offset-md-2 col-md-8 col-xs-12 custom-form">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-md-10 col-xs-12 py-4">

      <div class="row">
        <div class="col-12 text-center">
          <h1 class="mb-2">Editar Instrumento</h1>
          <hr class="teal accent-3 mb-4 mt-0 mx-auto border-dark" style="width: 200px;">
        </div>

        <div class="col-12">
          <%= render "instrumentos/form" %>
        </div>

      </div>

    </div>
  </div>
</section>

app/views/instrumentos/index.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="my-3 content py-3 ">

    <div class="w-100 text-center">
      <h1>Instrumentos</h1>
      <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
    </div>

    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
        <tr>
          <th class="text-center">Nombre</th>
          <th class="text-center">Tipo</th>
          <th class="text-center">Precio</th>
          <th class="text-center">Informacion</th>
          <th class="text-center" colspan="3">Acciones</th>
        </tr>
        </thead>

        <% @instrumento.each do |instrumento| %>
          <tbody>
            <tr>
              <td class="text-center align-middle"> <%= instrumento.nombre %> </td>

              <td class="text-center align-middle"> <%= instrumento.categorium.nombre %> </td>

              <td class="text-center align-middle"> <%= instrumento.precio %> </td>

              <td class="text-center align-middle"> <%= instrumento.informacion %> </td>

              <!-- Icono Detalles -->
              <td class="text-center align-middle">
                <%= link_to "Detalles", instrumento, class: "btn btn-info" %>
              </td>
              <!-- /Icono Detalles -->

              <!-- Icono Editar -->
              <td class="text-center align-middle">
                <%= link_to "Editar", edit_instrumento_path(instrumento.id), class: "btn btn-success" %>
              </td>
              <!-- /Icono Editar -->

              <!-- Icono Eliminar -->
              <td class="text-center align-middle">
                <%= link_to "Eliminar", instrumento, method: :delete, class: "btn btn-danger",
                              data: {confirm: '¿Está seguro de querer eliminar?'} %>
              </td>
              <!-- /Icono Eliminar -->

            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</section>

app/views/instrumentos/new.html.erb
<section class="offset-md-2 col-md-8 col-xs-12 custom-form">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-md-10 col-xs-12 py-4">

      <div class="row">
        <div class="col-12 text-center">
          <h1 class="mb-2">Nuevo Instrumento</h1>
          <hr class="teal accent-3 mb-4 mt-0 mx-auto border-dark" style="width: 200px;">
        </div>

        <div class="col-12">
          <%= render "instrumentos/form" %>
        </div>

      </div>

    </div>
  </div>
</section>

app/views/instrumentos/show.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-sm-12 py-4">
      <div class="w-100 text-center">
        <h1>Detalles instrumento</h1>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
      </div>

      <div class="row">
        <div class="col-md-3 mb-3 text-center">
          <%= image_tag(@instrumento.image, class: "rounded", style: "width: 200px") %>
        </div>

        <div class="col-md-5">
          <h4> <%= @instrumento.nombre %> </h4>
          <ul>
            <li class="col1"> <%= @instrumento.detalles %> </li>
          </ul>
        </div>

        <div class="col-md-4 mt-5">
          <table class="table">
            <tbody>
              <tr>
                <th>Color</th>
                <td> <%= @instrumento.color %> </td>
              </tr>
              <tr>
                <th>Material</th>
                <td> <%= @instrumento.material %> </td>
              </tr>
            </tbody>
          </table>

          <div class="col-md-8 text-center mt-3 pt-3">
            <!-- Icono Volver -->
            <td class="text-center align-middle">
              <%= link_to "Volver", instrumentos_path, class: "btn btn-dark ml-4" %>
            </td>
            <!-- /Icono Volver -->

            <!-- Icono Editar -->
            <td class="text-center align-middle">
              <%= link_to "Editar", edit_instrumento_path(@instrumento.id), class: "btn btn-success" %>
            </td>
            <!-- /Icono Editar -->
          </div>

        </div>

        <div class="col-md-4 text-center mt-3">
          <div class="alert alert-dark p-2 my-auto">
            <h5 class="my-auto"> <%= @instrumento.precio %> </h5>
          </div>
        </div>

      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicStoreRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid">
  <%= render "parciales/nav" %>
    <% if notice %>
      <p class="alert alert-primary"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/parciales/_nav.html.erb
<header class="offset-md-1 col-md-10 col-xs-12">

  <div class="d-flex flex-wrap align-items-center">
    <a class="mx-3" href="#">
      <h1 id="Titulo" class="text-dark">
        MusicStore
      </h1>
    </a>
  </div>

  <nav class="navbar navbar-expand-lg navbar-light bg-light mt-2">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Categorías", categorias_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Instrumentos", instrumentos_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Añadir Categoría", categorias_new_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Añadir instrumento", new_instrumento_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Usuarios", usuarios_index_path, class: "nav-link" %>
          </li>
        <li class="nav-item">
          <%= link_to "Añadir usuario", new_usuario_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/usuarios/_form.html.erb
<%= form_with(model: @usuario, url: usuarios_path, html: { method: :post} ,local: true) do |form| %>
  <% if @usuario.errors.any? %>
      <div class="alert-danger">
        <span>
          Se han escontrado
          <%= pluralize(@usuario.errors.count, "error") %>:
        </span>
        <ul>
          <% @usuario.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div class="row">
    <div class="col-md-6 col-xs-12">
      <div class="form-group">
        <%= form.label :tipo %>
        <%= form.text_field :tipo %>
      </div>
      <div class="form-group">
        <%= form.label :nombre %>
        <%= form.text_field :nombre %>
      </div>
      <div class="form-group">
        <%= form.label :apellidos %>
        <%= form.text_field :apellidos %>
      </div>
      <div class="form-group">
        <%= form.label :pais %>
        <%= form.text_field :pais %>
      </div>
      <div class="form-group">
        <%= form.label :localidad %>
        <%= form.text_field :localidad %>
      </div>
    </div>
    <div class="col-md-6 col-xs-12">
      <div class="form-group">
        <%= form.label :direccion %>
        <%= form.text_field :direccion %>
      </div>
      <div class="form-group">
        <%= form.label :codigoPostal %>
        <%= form.text_field :codigoPostal %>
      </div>
      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email %>
      </div>
      <div class="form-group">
        <%= form.label :contraseña %>
        <%= form.password_field :contraseña %>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center mb-2 mt-4">
    <%= form.submit "Guardar", class: "btn btn-dark" %>
    <%= link_to 'Cancelar', usuarios_index_path, class: "btn btn-primary ml-2" %>
  </div>
<% end %>

app/views/usuarios/index.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="my-3 content py-3 ">

    <div class="table-responsive">
      <div class="w-100 text-center">
        <h1>Usuarios</h1>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
      </div>

      <table class="table table-striped">
        <thead>
        <tr>
          <th class="text-center">Nombre</th>
          <th class="text-center">Apellidos</th>
          <th class="text-center">Pais</th>
          <th class="text-center">Correo</th>
          <th class="text-center" colspan="3">Acciones</th>
        </tr>
        </thead>

        <% @usuario.each do |usuario| %>
          <tbody>
          <tr>
            <td class="text-center align-middle"> <%= usuario.nombre %> </td>
            <td class="text-center align-middle"> <%= usuario.apellidos %> </td>
            <td class="text-center align-middle"> <%= usuario.pais %> </td>
            <td class="text-center align-middle"> <%= usuario.email %> </td>
            <td class="text-center align-middle">
              <%= link_to "Detalles", usuario, class: "btn btn-info " %>
              <%= link_to "Editar", edit_usuario_path(usuario.id), class: "btn btn-success ml-2" %>
              <%= link_to "Eliminar", usuario, method: :delete, class: "btn btn-danger ml-2",
              data: { confirm: '¿Desea eliminar?'} %>
            </td>
          </tr>

          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</section>

app/views/usuarios/login.html.erb
<section class="offset-lg-4 col-lg-4 offset-md-2 col-md-8 col-xs-12 custom-form">

  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-md-10 col-xs-12 py-4">
      <div class="row">
        <div class="col-12 text-center">
          <h1 class="mb-2"> Log in </h1>
          <hr class="teal accent-3 mb-4 mt-0 mx-auto border-dark" style="width: 200px;">
        </div>

        <div class="col-12">
          <%= form_for :usuario, url: usuarios_logged_path do |form| %>

            <div class="form-group">
              <%= form.label :nombre %>
              <%= form.text_field :nombre %>
            </div>

            <div class="form-group">
              <%= form.label :contraseña %>
              <%= form.password_field :contraseña %>
            </div>

            <div class="d-flex justify-content-center mb-2">
              <%= form.submit "Log in", class: "btn btn-dark" %>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/usuarios/show.html.erb
<section class="offset-md-2 col-md-8 col-xs-12">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-12 py-4">
      <div class="w-100 text-center mb-3">
        <h1>Información del usuario</h1>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
      </div>

      <div class="row">
        <div class="col-md-12 text-center">
          <div>
            <p> Tipo: <%= @usuario.tipo %> </p>
          </div>
          <div>
            <p> Nombre: <%= @usuario.nombre %> </p>
          </div>
          <div>
            <p> Apellidos: <%= @usuario.apellidos %> </p>
          </div>
          <div>
            <p> Pais: <%= @usuario.pais %> </p>
          </div>
          <div>
            <p> Localidad: <%= @usuario.localidad %> </p>
          </div>
          <div>
            <p> Dirección: <%= @usuario.direccion %> </p>
          </div>
          <div>
            <p> Código Postal: <%= @usuario.codigoPostal %> </p>
          </div>
          <div>
            <p> Correo: <%= @usuario.email %> </p>
          </div>
          <div>
            <p> Contraseña: <%= @usuario.contraseña %> </p>
          </div>
          <div>
              <%= link_to "Editar", edit_usuario_path(@usuario.id), class: "btn btn-success" %>
              <%= link_to "Eliminar", @usuario, method: :delete, class: "btn btn-danger" %>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>

app/views/usuarios/update.html.erb
<h1>Usuarios#update</h1>
<p>Find me in app/views/usuarios/update.html.erb</p>